# -*- coding: utf-8 -*-
"""trabalho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NDz1CzphyhDVwZY4XnxS19zwzI_57iqL
"""

#IBGE

nomes = []
idades = []
alturas = []

c = 1
i = 0

pessoas = int(input('quantas pessoas tem na casa'))
    
while pessoas >= c:
    nome = str(input('digite o seu nome'))
    nomes.append(nome)
    idade = int(input('quantos anos o senhor(a) ?'))
    idades.append(idade)
    altura = float(input('qual é sua altura ?'))
    alturas.append(altura)

    c+=1

while i <= pessoas -1:
    print(nomes[i], idades[i],alturas[i])
    i+=1